{{- if .Values.configEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azdevops-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azdevops-agent.name" . }}
    helm.sh/chart: {{ include "azdevops-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
data:
  {{- range $key, $value := .Values.configEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

